In [1]:
import numpy as np

## 1. DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.4],
              [4,5,6.4]])
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6.4]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
#a1.ndim, a2.ndim, a3.ndima

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.4
1  4.0  5.0  6.4

## 2. Creating Numpy array 

Once again we create an array with Numpy.

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

Creating an array filled with ones

In [17]:
ones = np.ones((2,3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

An array made of zeros

In [21]:
zeros = np.zeros( (2,3))

In [22]:
zeros


array([[0., 0., 0.],
       [0., 0., 0.]])

Creating a range array

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

Creating an array of random elements

In [24]:
random_array  = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 1, 4, 0, 5],
       [7, 0, 7, 0, 8],
       [3, 4, 2, 3, 3]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
random_array_two =  np.random.random((5,3))
random_array_two

array([[0.87363799, 0.78015588, 0.74161523],
       [0.60318249, 0.51329325, 0.62632138],
       [0.48451141, 0.10467607, 0.57682359],
       [0.14537883, 0.794226  , 0.10436727],
       [0.01711398, 0.01340171, 0.67103075]])

In [28]:
random_array_two.shape

(5, 3)

In [29]:
random_array_3 = np.random.rand(5,3)

In [30]:
    random_array_3

array([[0.22534714, 0.80605308, 0.58011395],
       [0.23931134, 0.95954002, 0.66885624],
       [0.54601553, 0.07967768, 0.89469674],
       [0.80690131, 0.96062887, 0.42755201],
       [0.06492484, 0.1661423 , 0.19217487]])

In [31]:
# Pseudo random numbers
np.random.seed(seed=999)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[0, 5, 1],
       [8, 1, 9],
       [3, 0, 5],
       [8, 8, 0],
       [5, 2, 5]])

In [32]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [33]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matrices

In [34]:
np.unique(random_array_4)

array([0, 1, 2, 3, 5, 8, 9])

In [35]:
a1

array([1, 2, 3])

In [36]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6.4]])

In [37]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [38]:
random_array_4

array([[0, 5, 1],
       [8, 1, 9],
       [3, 0, 5],
       [8, 8, 0],
       [5, 2, 5]])

In [39]:
a1[0]

1

In [40]:
a2[0]

array([1. , 2. , 3.4])

In [41]:
a2.shape

(2, 3)

In [42]:
a3.shape

(2, 3, 3)

In [43]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a2[1]

array([4. , 5. , 6.4])

In [45]:
a3[:]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [46]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [47]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [48]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [49]:
# Get tthe first 4 numbers of the inner most arrays
a4[:, :, :, :2]

array([[[[3, 5],
         [5, 0],
         [9, 6],
         [3, 3]],

        [[1, 0],
         [7, 9],
         [7, 7],
         [3, 1]],

        [[4, 3],
         [9, 1],
         [2, 5],
         [9, 9]]],


       [[[3, 0],
         [7, 2],
         [6, 6],
         [7, 1]],

        [[9, 9],
         [6, 8],
         [6, 1],
         [9, 8]],

        [[7, 5],
         [8, 1],
         [3, 7],
         [7, 5]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [52]:
a1

array([1, 2, 3])

In [54]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [55]:
a1 + ones

array([2., 3., 4.])

In [56]:
a1 - ones

array([0., 1., 2.])

In [57]:
a1 * ones

array([1., 2., 3.])

In [58]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6.4]])

In [59]:
a1 * a2

array([[ 1. ,  4. , 10.2],
       [ 4. , 10. , 19.2]])

In [60]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [61]:
# Need to reshape a2
#a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [62]:
a1 / ones

array([1., 2., 3.])

In [64]:
a2 / a1

array([[1.        , 1.        , 1.13333333],
       [4.        , 2.5       , 2.13333333]])

In [65]:
# Floor division removes the decimals
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [67]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6.4]])

In [66]:
a2 ** 2

array([[ 1.  ,  4.  , 11.56],
       [16.  , 25.  , 40.96]])

In [68]:
np.square(a2)

array([[ 1.  ,  4.  , 11.56],
       [16.  , 25.  , 40.96]])

In [69]:
np.add(a1, ones)

array([2., 3., 4.])

In [70]:
a1 % 2


array([1, 0, 1])